### ISSUE TITLE
how to make it play nice with nodemon?

### ISSUE THREAD

**Issue by davisford** [vohof/gulp-livereload#28]
I have a fullstack app with node/express on the backend, and I have a task to start the whole thing up using `gulp-nodemon` like so:

``` javascript
var reload = plugins.livereload();

gulp.task('nodemon', function() {
  plugins.nodemon({
    script: './src/server/bin/www',
    verbose: true,
    env: { 'NODE_ENV': 'development' },
    watch: './src/server',
    ext: 'js jade html css styl json',
    nodeArgs: ['--debug']
  }).on('restart', function () {
    // FIXME livereload -- this kills the browser session
    reload.changed('/');
  });
});
```

The livereload side works when the client files change.  I'm just piping the tasks that change to the livereload plugin, and when they change, the browser refreshes as expected.

The server side works -- at least to restart the server.  When nodemon detects a change in the server code, it kills and restarts the server.

Unfortunately, I can't get them both to play nicely together.  I tried above to trap into the `restart` event for nodemon, and just tell the plugin that the index changed, but what happens (in Chrome at least) is that the page is replaced immediately with Chrome's **No data received** error.  If I manually reload it, it comes up, so it appears to be a timing issue.

I was wondering if there is a recommended way to resolve this issue?

**Comment by lsiden** [comment]
FWIW this snippet:

    }).on('restart', setTimeout(function () {
        // livereload.changed(__dirname);
    }, 1000))

breaks my script.  After running "gulp serve" 

    Express server listening on port 3000
    [12:10:06] [nodemon] files triggering change check: gulpfile.js
    [12:10:06] [nodemon] matched rule: **/*.*
    [12:10:06] [nodemon] changes after filters (before/after): 1/1
    [12:10:06] [nodemon] restarting due to changes...
    [12:10:06] [nodemon] gulpfile.js
    [12:10:06] [nodemon] 
    [12:10:06] [nodemon] exiting
    /home/lsiden/pah/pahpublicbuild/cpservice/node_modules/gulp-nodemon/index.js:73
        if (!(tasks instanceof Array)) throw new Error('Expected task name or arra
                                             ^
    Error: Expected task name or array but found: [object Object]
        at run (/home/lsiden/pah/pahpublicbuild/cpservice/node_modules/gulp-nodemon/index.js:73:42)
        at null.<anonymous> (/home/lsiden/pah/pahpublicbuild/cpservice/node_modules/gulp-nodemon/index.js:58:22)
        at emit (events.js:129:20)
        at restartBus (/home/lsiden/pah/pahpublicbuild/cpservice/node_modules/gulp-nodemon/node_modules/nodemon/lib/monitor/watch.js:240:7)
        at filterAndRestart (/home/lsiden/pah/pahpublicbuild/cpservice/node_modules/gulp-nodemon/node_modules/nodemon/lib/monitor/watch.js:273:16)
        at /home/lsiden/pah/pahpublicbuild/cpservice/node_modules/gulp-nodemon/node_modules/nodemon/lib/monitor/watch.js:291:9
        at /home/lsiden/pah/pahpublicbuild/cpservice/node_modules/gulp-nodemon/node_modules/nodemon/lib/monitor/watch.js:100:9
        at ChildProcess.exithandler (child_process.js:742:7)
        at ChildProcess.emit (events.js:110:17)
        at maybeClose (child_process.js:1015:16)

This caused me hours of grief because the stack trace says nothing of livereload.  I discovered it after I exhausted every other possibility.

**Comment by vohof** [comment]
@lsiden Have you looked at this? https://github.com/vohof/gulp-livereload/tree/master/examples/nodemon

**Comment by lsiden** [comment]
Thanks.  The problem wasn't live-reload or nodemon; it was requirejs not playing nicely with gulp.  I'm new to both gulp and requirejs, and later found out that gulp has blacklisted requirejs.  So I have to try something else.
