### ISSUE TITLE
Got error listen EADDRINUSE

### ISSUE THREAD

**Issue by rodrigoea** [vohof/gulp-livereload#33]
I'm trying to solve a problem in a repository that uses gulp-livereload.

A few days ago I'm getting this error:

... Uhoh. Got error listen EADDRINUSE ...
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at Server.listen (net.js:1138:5)
    at Server.listen (/Applications/MAMP/htdocs/conferencia-orlando/site/node_modules/gulp-livereload/node_modules/tiny-lr/lib/server.js:138:15)
    at Function.exports.listen (/Applications/MAMP/htdocs/conferencia-orlando/site/node_modules/gulp-livereload/gulp-livereload.js:68:12)
    at Function.exports.changed (/Applications/MAMP/htdocs/conferencia-orlando/site/node_modules/gulp-livereload/gulp-livereload.js:88:20)
    at Transform.reload._transform (/Applications/MAMP/htdocs/conferencia-orlando/site/node_modules/gulp-livereload/gulp-livereload.js:24:13)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)

Here is the gulpfile.js:
https://github.com/samwx/html-skeleton-gulp/blob/master/gulpfile.js

How can I solve? Thanks.

**Comment by timbog80** [comment]
i got it to work but when i go to localhost:8088 it just prints "{"tinylr":"Welcome","version":"0.1.5"}"

**Comment by gthomas3** [comment]
had this issue and it was my sublime livereload extension. uninstalled the extension, re-ran gulp watch and that solved it

**Comment by nikitabanthiya** [comment]
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at Server.listen (net.js:1138:5)
    at EventEmitter.listen (/home/nikita/smart-car-node/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/home/nikita/smart-car-node/app.js:40:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
 

 how to solve? new to node

**Comment by michaelezehi** [comment]
@nikitabanthiya It means another process is using the port. You need to stop all instances of node running or shut down and restart, that might kill any process running. Try again, the issue should be solved.

**Comment by AbdullahDahmash** [comment]
pkill node solved my problem

**Comment by rahulthakur319** [comment]
This worked for me

Check which process is listening on that port using:
`fuser <port_no>/tcp`
then kill that process using
`kill -9 pid`
